# Naive Bayes Algorithm 
Machine learning algorithm that use Bayes' theorem to calculate the probability of a class label given a set of features. It is a simple and efficient algorithm that can be used for classification tasks.
Used for tasks such as:

1. Spam filtering
2. Sentiment analysis
3. Other natural language processing tasks.

* In Naive Bayes' algorithm , we assume that the features are independent of each other. This is known as the "Naive" assumption.
* The probability of a class label given a set of features is calculated using Bayes' theorem.

### Bayes' Theorem

Bayes' theorem is given by:

$$ P(A | B) = \frac{P(B | A) \cdot P(A)}{P(B)} $$

where:

- \( P(A | B) \) is the posterior probability.
- \( P(B | A) \) is the likelihood.
- \( P(A) \) is the prior probability.
- \( P(B) \) is the marginal probability.

In [3]:
# Import necessary Libraries
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load more libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:
# load the dataset
iris = load_iris()

# select feature and target from the dataset
X = iris.data
y = iris.target

# split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# call the model
gnb = GaussianNB()

# fit the model 
gnb.fit(X_train, y_train)

# predict the model 
y_pred = gnb.predict(X_test)

# evaluate the model 
print('accuracy_score', accuracy_score(y_test, y_pred))
print('confusion_matrix', confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

accuracy_score 1.0
confusion_matrix [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [13]:
#  Using MultinomialNB
mnb = MultinomialNB()

# fit the model 
mnb.fit(X_train, y_train)

# predict the model 
y_pred = mnb.predict(X_test)

# evaluate the model 
print("Accuracy score:",accuracy_score(y_test, y_pred))
print("Confusion Matrix:", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy score: 0.9
Confusion Matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [14]:
# call the model 
bnb = BernoulliNB()

# fit the model 
bnb.fit(X_train, y_train)

# make predictions
y_pred = bnb.predict(X_test)

# evalute the model 
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:" , confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy Score: 0.3
Confusion Matrix: [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



c:\Users\dv04i\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\dv04i\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\dv04i\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(r