# Numpy Introduction

### Array:
An array is a data structure that stores a collection of elements, each identified by an index or key. It's a fundamental data type in programming, allowing you to store and manipulate multiple values of the same type in a single variable.

In [117]:
# import libraries
import numpy as np 
import pandas as pd


In [118]:
a = np.array([[1, 2, 3],

              [4, 5, 6],
              
              [7, 8, 9],

              [10, 11, 12]                
             ])
pd.DataFrame(a)

a.shape

(4, 3)

In [119]:
a = np.arange(3)
a
a.shape

(3,)

In [120]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2]])

In [121]:
a3 = a2[np.newaxis, :]
a3
a3.shape

(1, 1, 3)

**1D array with the numpy**

In [122]:
a = np.arange(5)
a.shape

(5,)

In [123]:
a = np.array([1, 2, 3, 4, 5])
a.shape

(5,)

**2D array with the numpy**

In [124]:
b = np.random.rand(2, 5)
b

array([[0.60158393, 0.70669417, 0.94070209, 0.81229283, 0.31841812],
       [0.74645669, 0.60997058, 0.11969933, 0.74783598, 0.82375691]])

In [125]:
b = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)])
b.shape

(2, 5)

In [126]:
# zero 2D array 
zeros = np.zeros((3, 3)) # 3x3 array with all zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [127]:
# ones 2D array 
ones = np.ones((3, 3)) # 3x3 array with all ones
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:
# full 2D array 
full = np.full((3, 3), 5) # 3x3 array with all elements as 5
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [129]:
full.dtype

dtype('int64')

In [130]:
# creating the identity matrix
identity_matrix = np.eye(8) # 8x8 identity matrix
identity_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [131]:
identity_matrix.dtype # it is the datatype of elements present in the matrix or array

dtype('float64')

In [132]:
type(identity_matrix) # it is the datatype of the matrix  or array itself

numpy.ndarray

In [133]:
len(b) # lenght of array 

2

In [134]:
b.shape

(2, 5)

In [135]:
b.ndim # this is the attribute tell us the dimention of the array 

2

In [136]:
b.size # number of elements in the array 

10

## Basic operations of arrays

In [137]:
a

array([1, 2, 3, 4, 5])

In [138]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [139]:
g  = a - b
g

array([[ 0,  0,  0,  0,  0],
       [-5, -5, -5, -5, -5]])

In [153]:
# another way of substraction 
g = np.subtract(a,b)
g = np.array(a-b) # another method 
g

array([[ 0,  0,  0,  0,  0],
       [-5, -5, -5, -5, -5]])

In [141]:
a1 = np.arange(3) 
a1

array([0, 1, 2])

In [143]:
b1 = np.array([(1, 2, 3), (4, 5, 6)])
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
c1 = a1 + b1
c1

array([[1, 3, 5],
       [4, 6, 8]])

In [146]:
c2 = a1 - b1
c2

array([[-1, -1, -1],
       [-4, -4, -4]])

In [147]:
c3 = a1 * b1
c3

array([[ 0,  2,  6],
       [ 0,  5, 12]])

In [149]:
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
c3 - b1

array([[-1,  0,  3],
       [-4,  0,  6]])

In [155]:
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]])

## Square of each element 

In [ ]:
k = b ** 2
k

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

array([[ 0,  2,  6, 12, 20],
       [35, 47, 61, 77, 95]])