# **NumPy** 

In [2]:
# import ibraries
import numpy as np 
import pandas as pd

In [3]:
empty = np.empty((3,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [6]:
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [7]:
diff = np.arange(0, 23, 3)   #3 is the step size
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [8]:
lin = np.linspace(0, 10, num=5)  #5 points from 0 to 10 
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
lin_neg = np.linspace(0, -10, num=5)  #5 points from -10 to 10
lin_neg

array([  0. ,  -2.5,  -5. ,  -7.5, -10. ])

In [10]:
lin.dtype

dtype('float64')

In [11]:
x = np.ones(3, dtype=np.int64)
x

array([1, 1, 1])

In [12]:
x = np.arange(0, 22.6, 2.5, dtype=np.int64)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# sorting the array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# Concatenation of 2 arrays 
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c= np.concatenate((a,b))
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a = np.array([[1, 2], [3, 4]])  # this is 2D array 2x2
a

array([[1, 2],
       [3, 4]])

In [17]:
b = np.array([[5, 6]])       # this is also 2d array but 1x2
b

array([[5, 6]])

In [18]:
# Concatenat 2D ararys 
c = np.concatenate((a, b), axis=0)  # axis=0 means vertically, axis
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
d = np.array([[1, 2], [3, 4]]) # 2x2 matrix
d

array([[1, 2],
       [3, 4]])

In [20]:
a

array([[1, 2],
       [3, 4]])

In [21]:

e = np.concatenate((a, d), axis=1) # axis=1 means horizontally
e

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [22]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [25]:
array_example.ndim

3

In [26]:
array_example.size

24

In [27]:
array_example.shape

(3, 2, 4)

In [32]:
array_example.dtype

dtype('int64')

# Can we reshape the array 

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [30]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

# 3D arrays

In [34]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [41]:
# creating the 3D array of (3, 1, 4) shape
# images are also 3D array 

arr = np.array([[[1, 2, 3, 4]],

                [[5, 6, 7, 8]],

                [[9, 10, 11, 12]]])
arr.shape



(3, 1, 4)

In [ ]:
# we can also change the shape of 3D array but the number of element must be same 
np.reshape(arr, (3, 4)) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# we can also change the shape of 3D array but the number of element must be same 
np.reshape(arr, (6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [48]:
a[np.newaxis, :].shape

(1, 8)

In [49]:
a[:, np.newaxis].shape

(8, 1)

# Indexing and Slicing

In [50]:
a = np.array ([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
a[-4:-1]

array([5, 6, 7])

In [59]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a[a < 5]

array([1, 2, 3, 4])

In [62]:
a[a % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [63]:
# use two coditions
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
# using or condition
a[(a > 2) | (a < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])