# Numpy Indexing and Slicing

In [1]:
import numpy as np

In [2]:
a = np.array([ 1, 2, 3, 4, 5, 7])
a

array([1, 2, 3, 4, 5, 7])

In [3]:
a[0:3]

array([1, 2, 3])

In [4]:
a = a.reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 7]])

In [5]:
a[0]

array([1, 2, 3])

In [6]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [8]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [9]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [10]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [11]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [12]:
np.hsplit(x, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [13]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

---
# Matrix and Matrices

In [14]:
# create a 2x3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b= np.arange(0, 100, 2)
b.size

50

In [22]:
b = b.reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [37]:
b[0:4, -3:10] # first decide the rows and second decide the columns 

array([[14, 16, 18],
       [34, 36, 38],
       [54, 56, 58],
       [74, 76, 78]])

In [51]:
# this is how the matrix of 4x3 slice from the matrix of 5x10
b[1:, 3:6]

array([[26, 28, 30],
       [46, 48, 50],
       [66, 68, 70],
       [86, 88, 90]])

In [ ]:
b.max() # this tell us the maximum value in the matrix

np.int64(98)

In [56]:
b.max(axis=0) # this tell us the maximum value in the row

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [57]:
b.max(axis=1) # this tell us the maximum value in the column

array([18, 38, 58, 78, 98])

In [54]:
b.min()

np.int64(0)

In [55]:
b.sum()

np.int64(2450)

In [ ]:
m = np.arange(0, 20 , 2).reshape(5, 2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [ ]:
# now is want to add some row in this matrix but this is not adding the row this is the sum operation 
m + np.array([1, 2])

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16],
       [17, 20]])

In [63]:
np.vstack((m, np.array([50,80]))) # this is how we add some row to the matrix and hstack is use for adding the array in horizontal

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [50, 80]])

In [65]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [68]:
np.fliplr(b)

array([[18, 16, 14, 12, 10,  8,  6,  4,  2,  0],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [98, 96, 94, 92, 90, 88, 86, 84, 82, 80]])