# Numpy Indexing and Slicing

In [30]:
import numpy as np

In [31]:
a = np.array([ 1, 2, 3, 4, 5, 7])
a

array([1, 2, 3, 4, 5, 7])

In [32]:
a[0:3]

array([1, 2, 3])

In [33]:
a = a.reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 7]])

In [34]:
a[0]

array([1, 2, 3])

In [35]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [38]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [39]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [40]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [43]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [49]:
np.hsplit(x, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [50]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

---
# Matrix and Matrices

In [51]:
# create a 2x3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
b= np.arange(0, 100, 2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])